language: java
jdk:
  - oraclejdk8
script: "cd languages/Natlab; ant test"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mclab@sable.mcgill.ca
    on_success: change
    on_failure: always
  slack: sable-mclab:BCSCOEsSkQxkbBoNbuwrzVTC
